main = ".open-next/worker.js"
name = "thiss-link"

compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]

# The binding name must be "ASSETS" when the cache is enabled
assets = { directory = ".open-next/assets", binding = "ASSETS" }

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
